# Generated by Django 5.1.4 on 2025-05-12 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcentradoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.departamento')),
                ('jefeDepAcademico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefe_dep_academico', to='catalogos.autoridad')),
                ('presidenteAcademia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidente_academia', to='catalogos.autoridad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadModulosEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Taller', 'Taller'), ('Curso', 'Curso'), ('Conferencia', 'Conferencia')], max_length=200)),
                ('noProfesores', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fechaRealizacion', models.DateField()),
                ('carreras', models.ManyToManyField(to='catalogos.carrera', verbose_name='Carreras atendidas')),
                ('diagnostico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plancapacitacion.concentradodiagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Taller', 'Taller'), ('Curso', 'Curso'), ('Conferencia', 'Conferencia')], max_length=200)),
                ('noProfesores', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_realizacion', models.DateField()),
                ('diagnostico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plancapacitacion.concentradodiagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='DeteccionNecesidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.departamento')),
                ('jefeDepAcademico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefeDepAcademico', to='catalogos.autoridad')),
                ('presidenteAcademia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidenteAcademia', to='catalogos.autoridad')),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaDeteccionNecesidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('noProfesores', models.IntegerField()),
                ('periodoInicio', models.DateField()),
                ('periodoFin', models.DateField()),
                ('instructores', models.ManyToManyField(to='catalogos.instructor')),
                ('deteccionNecesidades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plancapacitacion.deteccionnecesidades')),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduccion', models.TextField()),
                ('justificacion', models.TextField()),
                ('servicio', models.CharField(choices=[('Curso', 'Curso'), ('Taller', 'Taller')], max_length=20)),
                ('elementosDidacticos', models.TextField()),
                ('competencias', models.TextField()),
                ('fuentes', models.TextField()),
                ('jefeDesarrolloAcademico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.autoridad')),
            ],
            options={
                'verbose_name_plural': 'Fichas técnicas',
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('instrumento', models.CharField(max_length=200)),
                ('fichaTecnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterios_evaluacion', to='plancapacitacion.fichatecnica', verbose_name='Ficha Técnica')),
            ],
            options={
                'verbose_name_plural': 'Criterios de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='ContenidoTematico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('tiempo', models.IntegerField()),
                ('actividades', models.TextField()),
                ('fichaTecnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_tematicos', to='plancapacitacion.fichatecnica', verbose_name='Ficha Técnica')),
            ],
            options={
                'verbose_name_plural': 'Contenidos Temáticos',
            },
        ),
        migrations.CreateModel(
            name='RegistroCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('objetivo', models.TextField(max_length=200)),
                ('horas', models.IntegerField()),
                ('aceptado', models.BooleanField(default=False)),
                ('dirigido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.dirigido')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.instructor')),
                ('perfilCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.perfilcurso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.periodo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.sede')),
            ],
            options={
                'verbose_name_plural': 'Registro de cursos',
                'db_table': 'plancapacitacion_registrocurso',
            },
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plancapacitacion.registrocurso'),
        ),
        migrations.CreateModel(
            name='ValidarCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plancapacitacion.registrocurso')),
            ],
            options={
                'verbose_name_plural': 'Validación de cursos',
            },
        ),
    ]
