# Generated by Django 5.1.4 on 2025-01-21 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('instructor', models.CharField(max_length=40)),
                ('justificacion', models.CharField(max_length=200)),
                ('objetivo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('horas', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=200)),
                ('competencias', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Ficha técnica',
            },
        ),
        migrations.CreateModel(
            name='registroCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('objetivo', models.TextField(max_length=200)),
                ('horas', models.IntegerField()),
                ('aceptado', models.BooleanField(default=False)),
                ('dirigido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.dirigido')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.instructor')),
                ('perfilCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.perfilcurso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.periodo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.sede')),
            ],
            options={
                'verbose_name_plural': 'Registro de cursos',
            },
        ),
        migrations.CreateModel(
            name='validarCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plancapacitacion.registrocurso')),
            ],
            options={
                'verbose_name_plural': 'Validación de cursos',
            },
        ),
    ]
