# Generated by Django 5.1.4 on 2024-12-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plancapacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocurso',
            name='horas',
            field=models.IntegerField(max_length=40),
        ),
    ]
