# Generated by Django 5.1.4 on 2025-02-06 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plancapacitacion', '0003_alter_fichatecnica_options_remove_fichatecnica_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidotematico',
            name='fichaTecnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_tematicos', to='plancapacitacion.fichatecnica', verbose_name='Ficha Técnica'),
        ),
        migrations.AlterField(
            model_name='criterioevaluacion',
            name='FichaTecnica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterios_evaluacion', to='plancapacitacion.fichatecnica', verbose_name='Ficha Técnica'),
        ),
    ]
