# Generated by Django 5.1.4 on 2025-02-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plancapacitacion', '0004_alter_contenidotematico_fichatecnica_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterioevaluacion',
            old_name='FichaTecnica',
            new_name='fichaTecnica',
        ),
    ]
