# Generated by Django 5.1.4 on 2025-02-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plancapacitacion', '0005_rename_fichatecnica_criterioevaluacion_fichatecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='justificacion',
            field=models.TextField(),
        ),
    ]
