# Generated by Django 5.1.4 on 2025-02-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plancapacitacion', '0007_fichatecnica_introduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichatecnica',
            name='competencias',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='elementosDidacticos',
            field=models.TextField(),
        ),
    ]
