# Generated by Django 5.1.4 on 2025-02-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plancapacitacion', '0008_alter_fichatecnica_competencias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidotematico',
            options={'verbose_name_plural': 'Contenidos Temáticos'},
        ),
        migrations.AlterModelOptions(
            name='criterioevaluacion',
            options={'verbose_name_plural': 'Criterios de Evaluación'},
        ),
    ]
