# Generated by Django 5.1.4 on 2025-03-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0030_carrera'),
        ('plancapacitacion', '0009_alter_contenidotematico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='jefeDesarrolloAcademico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.autoridad'),
        ),
    ]
