# Generated by Django 5.1.4 on 2025-03-29 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0030_carrera'),
        ('plancapacitacion', '0010_fichatecnica_jefedesarrolloacademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcentradoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(auto_now_add=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.departamento')),
                ('jefeDepAcademico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefe_dep_academico', to='catalogos.autoridad')),
                ('presidenteAcademia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidente_academia', to='catalogos.autoridad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadModulosEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Taller', 'Taller'), ('Curso', 'Curso'), ('Conferencia', 'Conferencia')], max_length=200)),
                ('noProfesores', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateField()),
                ('carreras', models.ManyToManyField(to='catalogos.carrera', verbose_name='Carreras atendidas')),
                ('diagnostico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plancapacitacion.concentradodiagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Taller', 'Taller'), ('Curso', 'Curso'), ('Conferencia', 'Conferencia')], max_length=200)),
                ('noProfesores', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_realizacion', models.DateField()),
                ('diagnostico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plancapacitacion.concentradodiagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='DeteccionNecesidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.departamento')),
                ('jefeDepAcademico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefeDepAcademico', to='catalogos.autoridad')),
                ('presidenteAcademia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidenteAcademia', to='catalogos.autoridad')),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaDeteccionNecesidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('noProfedores', models.IntegerField()),
                ('periodoInicio', models.DateField()),
                ('periodoFin', models.DateField()),
                ('deteccionNecesidades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plancapacitacion.deteccionnecesidades')),
            ],
        ),
    ]
