# Generated by Django 5.1.4 on 2025-04-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0031_rename_nombre_carrera_carrera'),
        ('plancapacitacion', '0012_rename_fecha_actividadmodulosespecialidad_fecharealizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturadeteccionnecesidades',
            name='instructores',
            field=models.ManyToManyField(to='catalogos.instructor'),
        ),
    ]
