# Generated by Django 5.1.4 on 2024-12-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('departamento', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Dirigido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('dirigido', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Dirigido a',
            },
        ),
        migrations.CreateModel(
            name='EstatusCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': ' Estatus de Curso ',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('grado', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Grado académico',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombreEdificio', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='PerfilCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('perfilCurso', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Curso',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('inicioPeriodo', models.DateField()),
                ('finPeriodo', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('sede', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('apPaterno', models.CharField(max_length=40)),
                ('apMaterno', models.CharField(max_length=40)),
                ('CURP', models.CharField(max_length=18)),
                ('RFC', models.CharField(max_length=13)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.departamento')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.genero')),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('apPaterno', models.CharField(max_length=40)),
                ('apMaterno', models.CharField(max_length=40)),
                ('fechaNac', models.DateField(blank=True, null=True)),
                ('CURP', models.CharField(max_length=18, null=True)),
                ('RFC', models.CharField(max_length=13, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('institucion', models.CharField(blank=True, max_length=40, null=True)),
                ('cedulaProf', models.CharField(max_length=8, null=True)),
                ('puesto', models.CharField(blank=True, max_length=40, null=True)),
                ('empresa', models.CharField(blank=True, max_length=40, null=True)),
                ('materia', models.CharField(blank=True, max_length=40, null=True)),
                ('periodo', models.CharField(blank=True, max_length=40, null=True)),
                ('curso', models.CharField(blank=True, max_length=40, null=True)),
                ('nombreEmpresa', models.CharField(blank=True, max_length=40, null=True)),
                ('duracionHoras', models.CharField(blank=True, max_length=40, null=True)),
                ('fechaParticipacion', models.DateField(blank=True, null=True)),
                ('grado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.gradoacademico')),
            ],
            options={
                'verbose_name_plural': 'Instructores',
            },
        ),
    ]
