# Generated by Django 5.1.4 on 2025-01-21 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclatura', models.CharField(blank=True, max_length=10, null=True)),
                ('numerodepartamento', models.CharField(blank=True, max_length=54, null=True)),
                ('departamento', models.CharField(max_length=40)),
                ('nombreJefe', models.CharField(blank=True, max_length=54, null=True)),
                ('apParternoJefe', models.CharField(blank=True, max_length=40, null=True)),
                ('apMaternoJefe', models.CharField(blank=True, max_length=40, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('paginaWeb', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apPaterno', models.CharField(max_length=40)),
                ('apMaterno', models.CharField(max_length=40)),
                ('puesto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Dirigido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirigido', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Dirigido a',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Grado académico',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('fechaNac', models.DateField(blank=True, null=True)),
                ('RFC', models.CharField(max_length=13, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('institucion', models.CharField(blank=True, max_length=40, null=True)),
                ('cedulaProf', models.CharField(max_length=8, null=True)),
                ('puesto', models.CharField(blank=True, max_length=40, null=True)),
                ('empresa', models.CharField(blank=True, max_length=60, null=True)),
                ('materia', models.CharField(blank=True, max_length=40, null=True)),
                ('periodo', models.CharField(blank=True, max_length=40, null=True)),
                ('curso', models.CharField(blank=True, max_length=40, null=True)),
                ('nombreEmpresa', models.CharField(blank=True, max_length=40, null=True)),
                ('duracionHoras', models.IntegerField(blank=True, null=True)),
                ('fechaParticipacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Instructores',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEdificio', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='PerfilCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfilCurso', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Curso',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.TextField(max_length=50)),
                ('inicioPeriodo', models.DateField()),
                ('finPeriodo', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('sede', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('fechaNac', models.DateField(blank=True, null=True)),
                ('RFC', models.CharField(max_length=13, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
