# Generated by Django 5.1.4 on 2025-01-21 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=40)),
                ('empresa', models.CharField(max_length=60)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to='catalogos.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=40)),
                ('grado', models.CharField(max_length=40)),
                ('cedulaProf', models.CharField(max_length=8, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formaciones_academicas', to='catalogos.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=40)),
                ('nombreEmpresa', models.CharField(max_length=40)),
                ('duracionHoras', models.IntegerField()),
                ('fechaParticipacion', models.DateField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_instructor', to='catalogos.instructor')),
            ],
        ),
    ]
