# Generated by Django 5.1.4 on 2024-12-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_horas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstatusCurso',
        ),
        migrations.DeleteModel(
            name='Horas',
        ),
        migrations.AlterField(
            model_name='periodo',
            name='clave',
            field=models.CharField(max_length=50),
        ),
    ]
