# Generated by Django 5.1.4 on 2025-01-21 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_experiencialaboral_formacionacademica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='cedulaProf',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='duracionHoras',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='fechaParticipacion',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='nombreEmpresa',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='puesto',
        ),
        migrations.CreateModel(
            name='ExperienciaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=40)),
                ('periodo', models.CharField(max_length=40)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_docentes', to='catalogos.instructor')),
            ],
        ),
    ]
