# Generated by Django 5.1.4 on 2024-12-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_delete_estatuscurso_delete_horas_alter_periodo_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='duracionHoras',
            field=models.IntegerField(blank=True, max_length=40, null=True),
        ),
    ]
