# Generated by Django 5.1.4 on 2024-12-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_alter_instructor_duracionhoras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='duracionHoras',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
