# Generated by Django 5.1.4 on 2025-01-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_participacioninstructor_periodofin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacioninstructor',
            name='fechaParticipacion',
        ),
    ]
