# Generated by Django 5.1.4 on 2025-01-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_instructor_duracionhoras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='dirigido',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='gradoacademico',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='perfilcurso',
            name='clave',
        ),
    ]
