# Generated by Django 5.1.4 on 2025-01-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_remove_participacioninstructor_fechaparticipacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacionacademica',
            name='grado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
