# Generated by Django 5.1.4 on 2025-01-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_remove_departamento_clave_remove_dirigido_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='empresa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='clave',
            field=models.TextField(max_length=50),
        ),
    ]
