# Generated by Django 5.1.4 on 2025-01-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_formacionacademica_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='clave',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
