# Generated by Django 5.1.4 on 2025-02-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_alter_periodo_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
