# Generated by Django 5.1.4 on 2025-02-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_director_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='estatus',
            field=models.BooleanField(),
        ),
    ]
