# Generated by Django 5.1.4 on 2025-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0015_alter_departamento_apmaternojefe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CalificacionValor', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Valor de Calificación',
                'verbose_name_plural': 'Valores de Calificación',
            },
        ),
    ]
