# Generated by Django 5.1.4 on 2025-02-21 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_valorcalificacion_delete_calificacionvalor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatosConstancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ImageField(upload_to='')),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FormatosDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ImageField(upload_to='')),
                ('footer', models.ImageField(upload_to='')),
                ('year', models.DateField()),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.departamento')),
            ],
        ),
    ]
