# Generated by Django 5.1.4 on 2025-02-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0019_rename_formatosconstancias_formatoconstancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoconstancia',
            name='vigente',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formatodepartamento',
            name='vigente',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
