# Generated by Django 5.1.4 on 2025-02-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0020_formatoconstancia_vigente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoconstancia',
            name='vigente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formatodepartamento',
            name='vigente',
            field=models.BooleanField(default=False),
        ),
    ]
