# Generated by Django 5.1.4 on 2025-02-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0021_alter_formatoconstancia_vigente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoconstancia',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='formatodepartamento',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
