# Generated by Django 5.1.4 on 2025-02-23 02:28

import catalogos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0023_alter_formatoconstancia_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoconstancia',
            name='header',
            field=models.ImageField(upload_to=catalogos.models.formato_constancia_upload_path),
        ),
        migrations.AlterField(
            model_name='formatodepartamento',
            name='footer',
            field=models.ImageField(upload_to=catalogos.models.formato_departamento_upload_path),
        ),
        migrations.AlterField(
            model_name='formatodepartamento',
            name='header',
            field=models.ImageField(upload_to=catalogos.models.formato_departamento_upload_path),
        ),
    ]
