# Generated by Django 5.1.4 on 2025-02-25 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0024_alter_formatoconstancia_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_masculino', models.CharField(max_length=200)),
                ('cargo_femenino', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='director',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cargoautoridad', verbose_name='Cargo'),
        ),
    ]
