# Generated by Django 5.1.4 on 2025-02-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0025_cargoautoridad_alter_director_puesto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Director',
            new_name='Autoridad',
        ),
    ]
