# Generated by Django 5.1.4 on 2025-02-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0026_rename_director_autoridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoridad',
            options={'verbose_name_plural': 'Autoridades'},
        ),
        migrations.AlterModelOptions(
            name='cargoautoridad',
            options={'verbose_name_plural': 'Cargos de Autoridad'},
        ),
        migrations.AddField(
            model_name='autoridad',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.genero', verbose_name='Género'),
        ),
    ]
