# Generated by Django 5.1.4 on 2025-02-25 21:38

import catalogos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0027_alter_autoridad_options_alter_cargoautoridad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoridad',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to=catalogos.models.firma_autoridad_upload_path),
        ),
    ]
