# Generated by Django 5.1.4 on 2025-02-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0028_autoridad_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorcalificacion',
            name='aprobatoria',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
