# Generated by Django 5.1.4 on 2025-03-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0029_valorcalificacion_aprobatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
    ]

