# Generated by Django 5.1.4 on 2025-03-16 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0030_carrera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='nombre',
            new_name='carrera',
        ),
    ]
