# Generated by Django 5.1.4 on 2024-12-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='curp',
            field=models.CharField(max_length=18, unique=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name_materno',
            field=models.CharField(max_length=50, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name_paterno',
            field=models.CharField(max_length=50, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Docente', 'Docente'), ('Instructor', 'Instructor')], max_length=50, verbose_name='Rol'),
        ),
    ]
