# Generated by Django 5.1.4 on 2025-01-21 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('plancapacitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('periodo', models.CharField(max_length=40)),
                ('lugar', models.CharField(max_length=40)),
                ('horas', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='oficioComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('fecha', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('lugar', models.CharField(max_length=40)),
                ('horas', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plancapacitacion.registrocurso')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.instructor')),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.lugar')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
            options={
                'verbose_name_plural': 'Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
            options={
                'verbose_name_plural': 'Inscripcion',
            },
        ),
    ]
