# Generated by Django 5.1.4 on 2025-05-12 18:44

import django.db.models.deletion
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('plancapacitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('asistio', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='OficioComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_oficio', models.CharField(max_length=40)),
                ('nomenclatura', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Oficios de comisión',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calificacion', models.DateField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.valorcalificacion')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='CriteriosSeleccionInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noSolicitud', models.CharField(max_length=40)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('criterio1', models.BooleanField(default=False)),
                ('criterio2', models.BooleanField(default=False)),
                ('criterio3', models.BooleanField(default=False)),
                ('criterio4', models.BooleanField(default=False)),
                ('criterio5', models.BooleanField(default=False)),
                ('criterio6', models.BooleanField(default=False)),
                ('criterio7', models.BooleanField(default=False)),
                ('criterio8', models.BooleanField(default=False)),
                ('criterio9', models.BooleanField(default=False)),
                ('criterio10', models.BooleanField(default=False)),
                ('total', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('aceptado', models.BooleanField(default=False, verbose_name='Aceptado')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plancapacitacion.registrocurso')),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluador_instructor', to='catalogos.autoridad', verbose_name='Evaluador')),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular', to='catalogos.autoridad', verbose_name='Titular')),
            ],
            options={
                'verbose_name': 'Criterio de selección de instructor',
                'verbose_name_plural': 'Criterios de selección de instructores',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('horaInicio', models.TimeField(blank=True, null=True)),
                ('horaFin', models.TimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plancapacitacion.registrocurso')),
                ('lugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.lugar')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.BooleanField(default=False)),
                ('archivo_evidencia', models.ImageField(blank=True, null=True, upload_to=eventos.models.evidencia_upload_path)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
            options={
                'verbose_name_plural': 'Evidencias',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
            options={
                'verbose_name_plural': 'Inscripcion',
            },
        ),
    ]
