# Generated by Django 5.1.1 on 2025-06-21 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_initial'),
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='inscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.inscripcion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.inscripcion'),
        ),
        migrations.AddField(
            model_name='oficiocomision',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.docente'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('evento', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('inscripcion', 'fecha_calificacion')},
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('inscripcion', 'fecha')},
        ),
    ]
