# Generated by Django 5.1.4 on 2024-12-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_delete_estatuscurso_delete_horas_alter_periodo_clave'),
        ('eventos', '0002_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='Instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.instructor'),
        ),
    ]
