# Generated by Django 5.1.4 on 2025-07-01 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='cupo_inscritos',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)], verbose_name='Cantidad de docentes a inscribir'),
        ),
    ]
