# Generated by Django 5.1.4 on 2024-12-16 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_delete_estatuscurso_delete_horas_alter_periodo_clave'),
        ('eventos', '0003_evento_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='Instructor',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.instructor'),
        ),
    ]
