# Generated by Django 5.1.4 on 2025-01-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='dias',
            field=models.TextField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], null=True),
        ),
    ]
