# Generated by Django 5.1.4 on 2025-01-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='dias',
        ),
    ]
