# Generated by Django 5.1.4 on 2025-01-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_inscripcion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hora',
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name_plural': 'Inscripcion'},
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='periodo',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
