# Generated by Django 5.1.4 on 2025-01-29 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_alter_periodo_clave'),
        ('eventos', '0007_inscripcion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.docente'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('evento', 'docente', 'fecha')},
        ),
        migrations.AlterModelTable(
            name='asistencia',
            table='eventos_asistencia',
        ),
    ]
