# Generated by Django 5.1.4 on 2025-01-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_alter_asistencia_options_asistencia_docente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asistencia',
        ),
    ]
