# Generated by Django 5.1.4 on 2025-01-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asistio',
            field=models.BooleanField(default=False),
        ),
    ]
