# Generated by Django 5.1.4 on 2025-01-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_asistencia_asistio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
