# Generated by Django 5.1.4 on 2025-02-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.BooleanField(default=False)),
                ('archivo_evidencia', models.ImageField(upload_to='evidencias/')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
        ),
        migrations.DeleteModel(
            name='calificacion',
        ),
    ]
