# Generated by Django 5.1.4 on 2025-02-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_evidencia_delete_calificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidencia',
            options={'verbose_name_plural': 'Evidencias'},
        ),
    ]
