# Generated by Django 5.1.4 on 2025-02-05 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_alter_evidencia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
    ]
