# Generated by Django 5.1.4 on 2025-02-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_alter_evidencia_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
    ]
