# Generated by Django 5.1.4 on 2025-02-06 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_alter_evidencia_archivo_evidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_calificacion', models.DateField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.inscripcion')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('inscripcion', 'fecha_calificacion')},
            },
        ),
    ]
