# Generated by Django 5.1.4 on 2025-02-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_valorcalificacion_delete_calificacionvalor'),
        ('eventos', '0017_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.valorcalificacion'),
        ),
    ]
