# Generated by Django 5.1.4 on 2025-02-13 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_valorcalificacion_delete_calificacionvalor'),
        ('eventos', '0019_alter_calificacion_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficiocomision',
            options={'verbose_name_plural': 'Oficios de comisión'},
        ),
        migrations.RenameField(
            model_name='oficiocomision',
            old_name='clave',
            new_name='no_oficio',
        ),
        migrations.RemoveField(
            model_name='oficiocomision',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='oficiocomision',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='oficiocomision',
            name='nombre',
        ),
        migrations.AddField(
            model_name='oficiocomision',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.docente'),
        ),
        migrations.AlterField(
            model_name='oficiocomision',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
