# Generated by Django 5.1.4 on 2025-02-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_alter_oficiocomision_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficiocomision',
            name='fecha',
            field=models.DateField(),
        ),
    ]
