# Generated by Django 5.1.4 on 2025-02-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_alter_oficiocomision_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficiocomision',
            name='no_oficio',
            field=models.CharField(max_length=40),
        ),
    ]
