# Generated by Django 5.1.4 on 2025-02-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_alter_oficiocomision_no_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficiocomision',
            name='nomenclatura',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
