# Generated by Django 5.1.4 on 2025-02-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0023_oficiocomision_nomenclatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='instructor',
        ),
    ]
