# Generated by Django 5.1.4 on 2025-03-01 03:06

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_remove_evento_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to=eventos.models.evidencia_upload_path),
        ),
    ]
