# Generated by Django 5.1.4 on 2025-03-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_alter_evidencia_archivo_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
    ]
