# Generated by Django 5.1.4 on 2025-03-02 05:16

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_alter_evidencia_archivo_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to=eventos.models.evidencia_upload_path),
        ),
    ]
