# Generated by Django 5.1.4 on 2025-03-29 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0030_carrera'),
        ('eventos', '0027_alter_evidencia_archivo_evidencia'),
        ('plancapacitacion', '0010_fichatecnica_jefedesarrolloacademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriosSeleccionInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noSolicitud', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('criterio1', models.BooleanField(default=False)),
                ('criterio2', models.BooleanField(default=False)),
                ('criterio3', models.BooleanField(default=False)),
                ('criterio4', models.BooleanField(default=False)),
                ('criterio5', models.BooleanField(default=False)),
                ('criterio6', models.BooleanField(default=False)),
                ('criterio7', models.BooleanField(default=False)),
                ('criterio8', models.BooleanField(default=False)),
                ('criterio9', models.BooleanField(default=False)),
                ('criterio10', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plancapacitacion.registrocurso')),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluador_instructor', to='catalogos.autoridad', verbose_name='Evaluador')),
                ('titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular', to='catalogos.autoridad', verbose_name='Titular')),
            ],
        ),
    ]
