# Generated by Django 5.1.4 on 2025-03-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0028_criteriosseleccioninstructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriosseleccioninstructor',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
