# Generated by Django 5.1.4 on 2025-03-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0029_criteriosseleccioninstructor_aceptado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteriosseleccioninstructor',
            options={'verbose_name': 'Criterio de selección de instructor', 'verbose_name_plural': 'Criterios de selección de instructores'},
        ),
        migrations.AddField(
            model_name='criteriosseleccioninstructor',
            name='total',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='criteriosseleccioninstructor',
            name='aceptado',
            field=models.BooleanField(default=False, verbose_name='Aceptado'),
        ),
    ]
