# Generated by Django 5.1.1 on 2025-06-21 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('encuesta', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('calificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.calificacion')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.autoridad')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.docente')),
                ('encuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
            ],
            options={
                'verbose_name': 'Constancia de docente',
                'verbose_name_plural': 'Constancias de docentes',
                'constraints': [models.UniqueConstraint(fields=('curso', 'docente'), name='unique_constancia_docente')],
            },
        ),
        migrations.CreateModel(
            name='ConstanciaInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.autoridad')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.instructor')),
            ],
            options={
                'verbose_name': 'Constancia de instructor',
                'verbose_name_plural': 'Constancias de instructores',
                'constraints': [models.UniqueConstraint(fields=('curso', 'instructor'), name='unique_constancia_instructor')],
            },
        ),
    ]
