# Generated by Django 5.1.4 on 2025-03-03 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0029_valorcalificacion_aprobatoria'),
        ('encuesta', '0004_alter_encuesta_curso1_alter_encuesta_curso2_and_more'),
        ('eventos', '0027_alter_evidencia_archivo_evidencia'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constanciadocente',
            name='calificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.calificacion'),
        ),
        migrations.AddField(
            model_name='constanciadocente',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.docente'),
        ),
        migrations.AddField(
            model_name='constanciadocente',
            name='encuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta'),
        ),
        migrations.AddField(
            model_name='constanciainstructor',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.instructor'),
        ),
        migrations.AlterField(
            model_name='constanciadocente',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
    ]
