# Generated by Django 5.1.4 on 2025-03-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_constanciadocente_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constanciadocente',
            options={'verbose_name': 'Constancia de docente', 'verbose_name_plural': 'Constancias de docentes'},
        ),
        migrations.AlterModelOptions(
            name='constanciainstructor',
            options={'verbose_name': 'Constancia de instructor', 'verbose_name_plural': 'Constancias de instructores'},
        ),
    ]
