# Generated by Django 5.1.4 on 2025-03-29 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0030_carrera'),
        ('reportes', '0003_alter_constanciadocente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constanciadocente',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.autoridad'),
        ),
        migrations.AddField(
            model_name='constanciainstructor',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.autoridad'),
        ),
    ]
