# Generated by Django 5.1.4 on 2025-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0030_carrera'),
        ('encuesta', '0004_alter_encuesta_curso1_alter_encuesta_curso2_and_more'),
        ('eventos', '0028_criteriosseleccioninstructor'),
        ('reportes', '0004_constanciadocente_director_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='constanciadocente',
            constraint=models.UniqueConstraint(fields=('curso', 'docente'), name='unique_constancia_docente'),
        ),
        migrations.AddConstraint(
            model_name='constanciainstructor',
            constraint=models.UniqueConstraint(fields=('curso', 'instructor'), name='unique_constancia_instructor'),
        ),
    ]
