# Generated by Django 5.1.1 on 2025-06-21 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encuesta', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='inscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='eventos.inscripcion'),
        ),
    ]
